server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    flyway:
      enabled: true
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 86400000
